"""Unit tests for change cards, store, and ExperimentCard conversion."""

from __future__ import annotations

import time
from pathlib import Path

import pytest

from optimizer.change_card import (
    ChangeCardStore,
    ConfidenceInfo,
    DiffHunk,
    ProposedChangeCard,
    _wrap_text,
)
from optimizer.experiments import ExperimentCard


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_card(
    card_id: str = "",
    title: str = "Rewrite root prompt",
    status: str = "pending",
    created_at: float | None = None,
) -> ProposedChangeCard:
    """Build a minimal ProposedChangeCard for tests."""
    return ProposedChangeCard(
        card_id=card_id,
        title=title,
        why="Quality improved with clearer instructions",
        diff_hunks=[
            DiffHunk(
                hunk_id="h1",
                surface="prompts.root",
                old_value="Be helpful.",
                new_value="Be helpful and concise.",
                status="pending",
            )
        ],
        metrics_before={"quality": 0.70, "safety": 1.0},
        metrics_after={"quality": 0.80, "safety": 1.0},
        confidence=ConfidenceInfo(p_value=0.03, effect_size=0.1),
        risk_class="low",
        cost_delta=0.001,
        experiment_card_id="exp-001",
        status=status,
        created_at=created_at or time.time(),
    )


def _make_experiment_card(
    experiment_id: str = "exp-001",
    hypothesis: str = "Rewrite root prompt for clarity",
) -> ExperimentCard:
    """Build a minimal ExperimentCard for conversion tests."""
    return ExperimentCard(
        experiment_id=experiment_id,
        created_at=time.time(),
        hypothesis=hypothesis,
        touched_surfaces=["instruction"],
        touched_agents=["root"],
        diff_summary="Rewrote root prompt",
        eval_set_versions={"golden": "abc123"},
        replay_set_hash="hash123",
        baseline_sha="sha_base",
        candidate_sha="sha_cand",
        risk_class="low",
        deployment_policy="pr_only",
        rollback_handle="rollback_001",
        total_experiment_cost=0.05,
        status="accepted",
        result_summary="Quality improved by 14%",
        operator_name="instruction_rewrite",
        baseline_scores={"quality": 0.70, "safety": 1.0, "cost": 0.002},
        candidate_scores={"quality": 0.80, "safety": 1.0, "cost": 0.003},
        significance_p_value=0.03,
        significance_delta=0.1,
    )


# ---------------------------------------------------------------------------
# ProposedChangeCard dataclass tests
# ---------------------------------------------------------------------------


class TestProposedChangeCard:
    def test_auto_generates_card_id(self) -> None:
        card = ProposedChangeCard(title="test")
        assert card.card_id != ""
        assert len(card.card_id) == 8

    def test_preserves_explicit_card_id(self) -> None:
        card = ProposedChangeCard(card_id="my-id", title="test")
        assert card.card_id == "my-id"

    def test_to_dict_round_trip(self) -> None:
        card = _make_card(card_id="rt-001")
        data = card.to_dict()
        restored = ProposedChangeCard.from_dict(data)

        assert restored.card_id == "rt-001"
        assert restored.title == card.title
        assert restored.why == card.why
        assert len(restored.diff_hunks) == 1
        assert restored.diff_hunks[0].surface == "prompts.root"
        assert restored.metrics_before == card.metrics_before
        assert restored.metrics_after == card.metrics_after
        assert restored.confidence.p_value == pytest.approx(0.03)
        assert restored.confidence.effect_size == pytest.approx(0.1)
        assert restored.risk_class == "low"
        assert restored.status == "pending"
        assert restored.experiment_card_id == "exp-001"

    def test_from_dict_defaults(self) -> None:
        card = ProposedChangeCard.from_dict({})
        # card_id auto-generated by __post_init__ when empty string passed
        assert len(card.card_id) == 8
        assert card.status == "pending"
        assert card.confidence.p_value == 1.0

    def test_from_experiment_card(self) -> None:
        exp = _make_experiment_card()
        card = ProposedChangeCard.from_experiment_card(exp)

        assert card.title == exp.hypothesis
        assert card.why == exp.result_summary
        assert card.experiment_card_id == "exp-001"
        assert card.risk_class == "low"
        assert card.confidence.p_value == pytest.approx(0.03)
        assert card.confidence.effect_size == pytest.approx(0.1)
        assert card.cost_delta == pytest.approx(0.001)
        assert len(card.diff_hunks) == 1
        assert "instruction" in card.diff_hunks[0].surface
        assert "5%" in card.rollback_condition  # low risk -> 5% threshold

    def test_from_experiment_card_high_risk(self) -> None:
        exp = _make_experiment_card()
        exp.risk_class = "high"
        card = ProposedChangeCard.from_experiment_card(exp)
        assert "3%" in card.rollback_condition  # high risk -> 3% threshold

    def test_from_experiment_card_with_memory_context(self) -> None:
        exp = _make_experiment_card()
        card = ProposedChangeCard.from_experiment_card(
            exp, memory_context="Focus on conciseness"
        )
        assert card.memory_context == "Focus on conciseness"

    def test_from_experiment_card_override_scores(self) -> None:
        exp = _make_experiment_card()
        card = ProposedChangeCard.from_experiment_card(
            exp,
            baseline_scores={"quality": 0.5},
            candidate_scores={"quality": 0.9},
        )
        assert card.metrics_before == {"quality": 0.5}
        assert card.metrics_after == {"quality": 0.9}

    def test_from_experiment_card_no_diff_summary(self) -> None:
        exp = _make_experiment_card()
        exp.diff_summary = ""
        card = ProposedChangeCard.from_experiment_card(exp)
        assert len(card.diff_hunks) == 0

    def test_from_experiment_card_uses_hypothesis_as_fallback_why(self) -> None:
        exp = _make_experiment_card()
        exp.result_summary = ""
        card = ProposedChangeCard.from_experiment_card(exp)
        assert card.why == exp.hypothesis


# ---------------------------------------------------------------------------
# DiffHunk tests
# ---------------------------------------------------------------------------


class TestDiffHunk:
    def test_to_dict_from_dict_round_trip(self) -> None:
        hunk = DiffHunk(
            hunk_id="h1",
            surface="prompts.root",
            old_value="old",
            new_value="new",
            status="accepted",
        )
        data = hunk.to_dict()
        restored = DiffHunk.from_dict(data)
        assert restored.hunk_id == "h1"
        assert restored.status == "accepted"

    def test_from_dict_defaults(self) -> None:
        hunk = DiffHunk.from_dict({})
        assert hunk.status == "pending"
        assert hunk.hunk_id == ""


# ---------------------------------------------------------------------------
# Rendering tests
# ---------------------------------------------------------------------------


class TestRendering:
    def test_to_terminal_contains_title(self) -> None:
        card = _make_card()
        output = card.to_terminal()
        assert "Rewrite root prompt" in output
        assert "WHY:" in output
        assert "METRICS" in output
        assert "CONFIDENCE" in output
        assert "PENDING" in output

    def test_to_terminal_with_memory_context(self) -> None:
        card = _make_card()
        card.memory_context = "Prioritize conciseness"
        output = card.to_terminal()
        assert "AUTOAGENT.md" in output

    def test_to_markdown_contains_sections(self) -> None:
        card = _make_card(card_id="md-001")
        md = card.to_markdown()
        assert "# Proposed Change: Rewrite root prompt" in md
        assert "## Why" in md
        assert "## Metrics" in md
        assert "## Confidence" in md
        assert "md-001" in md

    def test_to_markdown_with_memory(self) -> None:
        card = _make_card()
        card.memory_context = "Focus on safety"
        md = card.to_markdown()
        assert "AUTOAGENT.md" in md
        assert "Focus on safety" in md


# ---------------------------------------------------------------------------
# ChangeCardStore tests
# ---------------------------------------------------------------------------


class TestChangeCardStore:
    def test_save_and_get(self, tmp_path: Path) -> None:
        store = ChangeCardStore(db_path=str(tmp_path / "cards.db"))
        card = _make_card(card_id="store-001")
        store.save(card)

        retrieved = store.get("store-001")
        assert retrieved is not None
        assert retrieved.card_id == "store-001"
        assert retrieved.title == card.title
        assert len(retrieved.diff_hunks) == 1

    def test_get_nonexistent(self, tmp_path: Path) -> None:
        store = ChangeCardStore(db_path=str(tmp_path / "cards.db"))
        assert store.get("nope") is None

    def test_list_pending(self, tmp_path: Path) -> None:
        store = ChangeCardStore(db_path=str(tmp_path / "cards.db"))
        now = time.time()
        store.save(_make_card(card_id="p1", status="pending", created_at=now))
        store.save(
            _make_card(card_id="p2", status="pending", created_at=now + 1)
        )
        store.save(
            _make_card(card_id="a1", status="applied", created_at=now + 2)
        )

        pending = store.list_pending()
        assert len(pending) == 2
        assert all(c.status == "pending" for c in pending)
        # Newest first
        assert pending[0].card_id == "p2"

    def test_list_all(self, tmp_path: Path) -> None:
        store = ChangeCardStore(db_path=str(tmp_path / "cards.db"))
        now = time.time()
        store.save(_make_card(card_id="c1", status="pending", created_at=now))
        store.save(
            _make_card(card_id="c2", status="applied", created_at=now + 1)
        )
        store.save(
            _make_card(card_id="c3", status="rejected", created_at=now + 2)
        )

        all_cards = store.list_all()
        assert len(all_cards) == 3
        assert all_cards[0].card_id == "c3"

    def test_update_status(self, tmp_path: Path) -> None:
        store = ChangeCardStore(db_path=str(tmp_path / "cards.db"))
        store.save(_make_card(card_id="us-001", status="pending"))

        result = store.update_status("us-001", "rejected", reason="Too risky")
        assert result is True

        card = store.get("us-001")
        assert card is not None
        assert card.status == "rejected"
        assert card.rejection_reason == "Too risky"

    def test_update_status_nonexistent(self, tmp_path: Path) -> None:
        store = ChangeCardStore(db_path=str(tmp_path / "cards.db"))
        assert store.update_status("nope", "applied") is False

    def test_update_hunk_status(self, tmp_path: Path) -> None:
        store = ChangeCardStore(db_path=str(tmp_path / "cards.db"))
        store.save(_make_card(card_id="uh-001"))

        result = store.update_hunk_status("uh-001", "h1", "accepted")
        assert result is True

        card = store.get("uh-001")
        assert card is not None
        assert card.diff_hunks[0].status == "accepted"

    def test_update_hunk_status_bad_hunk_id(self, tmp_path: Path) -> None:
        store = ChangeCardStore(db_path=str(tmp_path / "cards.db"))
        store.save(_make_card(card_id="uh-002"))
        assert store.update_hunk_status("uh-002", "bad-id", "accepted") is False

    def test_update_hunk_status_bad_card_id(self, tmp_path: Path) -> None:
        store = ChangeCardStore(db_path=str(tmp_path / "cards.db"))
        assert store.update_hunk_status("nope", "h1", "accepted") is False


# ---------------------------------------------------------------------------
# Utility tests
# ---------------------------------------------------------------------------


class TestWrapText:
    def test_wraps_long_text(self) -> None:
        result = _wrap_text("one two three four five", 10)
        assert len(result) >= 2

    def test_empty_text(self) -> None:
        result = _wrap_text("", 40)
        assert result == [""]

    def test_single_word(self) -> None:
        result = _wrap_text("hello", 40)
        assert result == ["hello"]
