"""Project file generator for coding agents.

Generates CLAUDE.md, AGENTS.md, and per-skill markdown files that give
AI coding assistants (Claude Code, Codex, etc.) structured context about
the AutoAgent project they are working in.
"""
from __future__ import annotations

import os
from datetime import datetime, timezone
from typing import Any


class ProjectFileGenerator:
    """Generates and auto-updates coding-agent project configuration files."""

    # ------------------------------------------------------------------
    # Public generators
    # ------------------------------------------------------------------

    def generate_claude_md(self, project_config: dict[str, Any]) -> str:
        """Generate the content of a CLAUDE.md file for the project.

        Parameters
        ----------
        project_config:
            Dict with optional keys: name, description, stack, commands,
            notes, skills, guardrails, conventions.
        """
        name = project_config.get("name", "AutoAgent VNextCC")
        description = project_config.get(
            "description",
            "AI agent CI/CD system with composable optimization and guardrails.",
        )
        stack = project_config.get("stack", [])
        commands = project_config.get("commands", {})
        notes = project_config.get("notes", [])
        skills = project_config.get("skills", [])
        guardrails = project_config.get("guardrails", [])
        conventions = project_config.get("conventions", [])

        lines: list[str] = [
            f"# {name}",
            "",
            description,
            "",
        ]

        # Stack
        if stack:
            lines += ["## Tech Stack", ""]
            for item in stack:
                lines.append(f"- {item}")
            lines.append("")

        # Commands
        if commands:
            lines += ["## Common Commands", ""]
            for cmd_name, cmd_value in commands.items():
                lines.append(f"### {cmd_name}")
                lines.append(f"```bash")
                lines.append(cmd_value)
                lines.append("```")
                lines.append("")

        # Skills
        if skills:
            lines += ["## Available Skills", ""]
            for skill in skills:
                if isinstance(skill, dict):
                    lines.append(f"- **{skill.get('name', '')}**: {skill.get('description', '')}")
                else:
                    lines.append(f"- {skill}")
            lines.append("")

        # Guardrails
        if guardrails:
            lines += ["## Guardrails", ""]
            for g in guardrails:
                if isinstance(g, dict):
                    lines.append(f"- **{g.get('name', '')}** ({g.get('severity', 'warn')}): {g.get('description', '')}")
                else:
                    lines.append(f"- {g}")
            lines.append("")

        # Conventions
        if conventions:
            lines += ["## Conventions", ""]
            for c in conventions:
                lines.append(f"- {c}")
            lines.append("")

        # Notes
        if notes:
            lines += ["## Notes", ""]
            for note in notes:
                lines.append(f"> {note}")
            lines.append("")

        lines += [
            f"*Generated by AutoAgent ProjectFileGenerator on {_now_iso()}*",
            "",
        ]
        return "\n".join(lines)

    def generate_agents_md(self, project_config: dict[str, Any]) -> str:
        """Generate the content of an AGENTS.md file for the project.

        Parameters
        ----------
        project_config:
            Dict with optional keys: name, agents, tools, evals, workflows.
        """
        name = project_config.get("name", "AutoAgent VNextCC")
        agents = project_config.get("agents", [])
        tools = project_config.get("tools", [])
        evals = project_config.get("evals", {})
        workflows = project_config.get("workflows", [])

        lines: list[str] = [
            f"# Agents — {name}",
            "",
            "This file describes the agent topology, available tools, eval suites, "
            "and workflows for this AutoAgent project.",
            "",
        ]

        # Agents
        if agents:
            lines += ["## Agent Topology", ""]
            for agent in agents:
                if isinstance(agent, dict):
                    aname = agent.get("name", "unnamed")
                    atype = agent.get("type", "specialist")
                    adesc = agent.get("description", "")
                    lines.append(f"### {aname} ({atype})")
                    if adesc:
                        lines.append(adesc)
                    lines.append("")
                else:
                    lines.append(f"- {agent}")
            lines.append("")

        # Tools
        if tools:
            lines += ["## MCP Tools", ""]
            for tool in tools:
                if isinstance(tool, dict):
                    lines.append(f"- **{tool.get('name', '')}**: {tool.get('description', '')}")
                else:
                    lines.append(f"- {tool}")
            lines.append("")

        # Evals
        if evals:
            lines += ["## Eval Suites", ""]
            if isinstance(evals, dict):
                for suite_name, suite_info in evals.items():
                    lines.append(f"### {suite_name}")
                    if isinstance(suite_info, dict):
                        for k, v in suite_info.items():
                            lines.append(f"- {k}: {v}")
                    else:
                        lines.append(str(suite_info))
                    lines.append("")
            lines.append("")

        # Workflows
        if workflows:
            lines += ["## Workflows", ""]
            for wf in workflows:
                if isinstance(wf, dict):
                    lines.append(f"### {wf.get('name', 'unnamed')}")
                    lines.append(wf.get("description", ""))
                    steps = wf.get("steps", [])
                    for i, step in enumerate(steps, 1):
                        lines.append(f"{i}. {step}")
                    lines.append("")
                else:
                    lines.append(f"- {wf}")
            lines.append("")

        lines += [
            f"*Generated by AutoAgent ProjectFileGenerator on {_now_iso()}*",
            "",
        ]
        return "\n".join(lines)

    def generate_skill_md_buildtime(
        self,
        skill_name: str,
        skill_config: dict[str, Any],
    ) -> str:
        """Generate a per-skill markdown file for build-time reference.

        Parameters
        ----------
        skill_name:
            Name of the skill (used as the heading).
        skill_config:
            Dict with optional keys: description, instructions, validators,
            scripts, examples, version, category.
        """
        description = skill_config.get("description", f"Skill: {skill_name}")
        instructions = skill_config.get("instructions", "")
        validators = skill_config.get("validators", [])
        scripts = skill_config.get("scripts", {})
        examples = skill_config.get("examples", [])
        version = skill_config.get("version", "1.0.0")
        category = skill_config.get("category", "general")

        lines: list[str] = [
            f"# Skill: {skill_name}",
            "",
            f"**Version:** {version}  ",
            f"**Category:** {category}",
            "",
            description,
            "",
        ]

        if instructions:
            lines += ["## Instructions", "", instructions, ""]

        if validators:
            lines += ["## Validators", ""]
            for v in validators:
                lines.append(f"- `{v}`")
            lines.append("")

        if scripts:
            lines += ["## Scripts", ""]
            for sname, scode in scripts.items():
                lines.append(f"### {sname}")
                lines.append("```python")
                lines.append(scode)
                lines.append("```")
                lines.append("")

        if examples:
            lines += ["## Examples", ""]
            for i, ex in enumerate(examples, 1):
                if isinstance(ex, dict):
                    lines.append(f"### Example {i}")
                    if "input" in ex:
                        lines.append(f"**Input:** {ex['input']}")
                    if "output" in ex:
                        lines.append(f"**Output:** {ex['output']}")
                    lines.append("")
                else:
                    lines.append(f"{i}. {ex}")
            lines.append("")

        lines += [
            f"*Generated by AutoAgent ProjectFileGenerator on {_now_iso()}*",
            "",
        ]
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Auto-update
    # ------------------------------------------------------------------

    def auto_update(self, project_dir: str) -> list[str]:
        """Regenerate project files in *project_dir* and return changed paths.

        Files updated:
        - ``<project_dir>/CLAUDE.md``
        - ``<project_dir>/AGENTS.md``
        - ``<project_dir>/skills/*.md`` for each discovered skill
        """
        context = self._get_project_context(project_dir)
        changed: list[str] = []

        # CLAUDE.md
        claude_path = os.path.join(project_dir, "CLAUDE.md")
        claude_content = self.generate_claude_md(context)
        if _write_if_changed(claude_path, claude_content):
            changed.append(claude_path)

        # AGENTS.md
        agents_path = os.path.join(project_dir, "AGENTS.md")
        agents_content = self.generate_agents_md(context)
        if _write_if_changed(agents_path, agents_content):
            changed.append(agents_path)

        # Per-skill files
        skills_dir = os.path.join(project_dir, "skills")
        skills = context.get("skills", [])
        for skill in skills:
            if isinstance(skill, dict) and skill.get("name"):
                sname = skill["name"]
                skill_md = self.generate_skill_md_buildtime(sname, skill)
                skill_path = os.path.join(skills_dir, f"{sname}.md")
                os.makedirs(skills_dir, exist_ok=True)
                if _write_if_changed(skill_path, skill_md):
                    changed.append(skill_path)

        return changed

    def _get_project_context(self, project_dir: str) -> dict[str, Any]:
        """Build a project context dict by introspecting *project_dir*.

        Reads pyproject.toml / setup.cfg for the project name, scans for
        skill configs, and gathers MCP tool names from the tool registry.
        """
        context: dict[str, Any] = {
            "name": os.path.basename(os.path.abspath(project_dir)),
            "description": "AutoAgent VNextCC — AI agent CI/CD with composable optimization.",
            "stack": [
                "Python 3.11+",
                "Google ADK / Anthropic SDK",
                "SQLite (conversations, memory, registry)",
                "MCP JSON-RPC 2.0",
            ],
            "commands": {
                "Run evals": "python -m autoagent eval",
                "Start MCP server (stdio)": "python -m autoagent mcp-server",
                "Start MCP server (HTTP)": "python -m autoagent mcp-server --http --port 3000",
                "Run tests": "pytest",
            },
            "conventions": [
                "All domain objects implement to_dict() / from_dict().",
                "MCP tools take **kwargs and return dict.",
                "Guardrails are composable via GuardrailChain.",
                "Eval cases use EvalSuiteType to declare intent.",
            ],
        }

        # Try to read pyproject.toml for project name
        pyproject = os.path.join(project_dir, "pyproject.toml")
        if os.path.isfile(pyproject):
            try:
                import tomllib  # type: ignore[import]
                with open(pyproject, "rb") as f:
                    data = tomllib.load(f)
                pname = (
                    data.get("project", {}).get("name")
                    or data.get("tool", {}).get("poetry", {}).get("name")
                )
                if pname:
                    context["name"] = pname
                pdesc = (
                    data.get("project", {}).get("description")
                    or data.get("tool", {}).get("poetry", {}).get("description")
                )
                if pdesc:
                    context["description"] = pdesc
            except Exception:
                pass

        # Collect MCP tools
        try:
            from mcp_server.tools import TOOL_REGISTRY
            context["tools"] = [
                {"name": name, "description": defn.description}
                for name, (_, defn) in TOOL_REGISTRY.items()
            ]
        except Exception:
            context["tools"] = []

        # Collect skills from registry
        try:
            import os as _os
            from registry.skill_store import SkillStore
            store = SkillStore(db_path=_os.environ.get("AUTOAGENT_REGISTRY_DB", "registry.db"))
            raw_skills = store.recommend()
            context["skills"] = [
                {
                    "name": s.name,
                    "description": getattr(s, "description", ""),
                    "category": getattr(s, "category", "general"),
                }
                for s in raw_skills
            ]
            store.close()
        except Exception:
            context["skills"] = []

        return context


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _write_if_changed(path: str, content: str) -> bool:
    """Write *content* to *path* only if it differs from the existing file.

    Returns True if the file was written (new or changed), False otherwise.
    """
    try:
        if os.path.isfile(path):
            with open(path) as f:
                existing = f.read()
            if existing == content:
                return False
    except OSError:
        pass
    try:
        os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
        with open(path, "w") as f:
            f.write(content)
        return True
    except OSError:
        return False
